# Aula 06 – Concatenação de Dados com Pandas

## Objetivo
Aprender a unir múltiplos datasets (mensais) para formar uma base consolidada.

## O que será abordado:
- concat()
- pivot()
- União de datasets
- Estruturação de bases maiores
- Boas práticas

## 1. Importando bibliotecas

In [27]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

## 2. Carregando os dados
Vamos carregar três bases:
- Dezembro
- Janeiro
- Fevereiro

In [28]:
caminho_arquivo = r"C:\Users\Joao.Maria\Documents\Analise\Base\Base_analitica_vendas_periodo.xlsx"

In [29]:
base_venda_dezembro = pd.read_excel(caminho_arquivo, sheet_name="Dez")
base_venda_janeiro = pd.read_excel(caminho_arquivo, sheet_name="Jan")
base_venda_fevereiro = pd.read_excel(caminho_arquivo, sheet_name="Fev")

## 3. Analisando estrutura das bases

In [30]:
base_venda_dezembro.columns

Index(['DATA', 'CODIGOCLIENTE', 'DESCRICAOCLIENTE', 'CODIGOGRUPOPRODUTO',
       'DESCRICAOGRUPOPRODUTO', 'CODIGOPRODUTO', 'NOMEPRODUTO',
       'TIPOFATURAMENTO', 'DESCRICAOTIPOFATURAMENTO', 'VOLUME',
       'VALORLIQUIDO'],
      dtype='str')

In [31]:
base_venda_janeiro.columns

Index(['DATAEMISSAO', 'CODIGOCLIENTE', 'DESCRICAOCLIENTE',
       'CODIGOGRUPOPRODUTO', 'DESCRICAOGRUPOPRODUTO', 'CODIGOPRODUTO',
       'NOMEPRODUTO', 'TIPOFATURAMENTO', 'DESCRICAOTIPOFATURAMENTO', 'VOLUME',
       'VALORLIQUIDO'],
      dtype='str')

In [32]:
base_venda_fevereiro.columns

Index(['DATAEMISSAO', 'CODIGOCLIENTE', 'DESCRICAOCLIENTE',
       'CODIGOGRUPOPRODUTO', 'DESCRICAOGRUPOPRODUTO', 'CODIGOPRODUTO',
       'NOMEPRODUTO', 'TIPOFATURAMENTO', 'DESCRICAOTIPOFATURAMENTO', 'VOLUME',
       'VALORLIQUIDO'],
      dtype='str')

## 4. Concatenando os datasets

In [33]:
base_venda_dezembro["MES"] = "Dezembro"
base_venda_janeiro["MES"] = "Janeiro"
base_venda_fevereiro["MES"] = "Fevereiro"

In [34]:
base_vendas_periodo = pd.concat([
    base_venda_dezembro, 
    base_venda_janeiro, 
    base_venda_fevereiro
], ignore_index=True)

In [35]:
base_vendas_periodo

,DATA,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,MES,DATAEMISSAO
0,2025-12-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,1,VENDA,1315,"7,311.40",Dezembro,NaT
1,2025-12-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013060,Bebidas Prontas para Consumo (RTD),10005769,Pack 4 Unidades Gin Tônica 269ml,1,VENDA,730,"4,015.00",Dezembro,NaT
2,2025-12-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015857,Drink Misto Peach 269ml,1,VENDA,2000,"28,440.00",Dezembro,NaT
3,2025-12-01,10001683,ATACADISTA BRINDE AMIGO,90013060,Bebidas Prontas para Consumo (RTD),10005769,Pack 4 Unidades Gin Tônica 269ml,1,VENDA,26,377.26,Dezembro,NaT
4,2025-12-01,10004002,COMERCIAL MUNDO DAS BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015849,Drink Misto Blueberry 330ml,3,BONIFICAÇÃO,15,55.05,Dezembro,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106659,NaT,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503405,Energéticos de Alta Performance,10023656,Shot Energético Ultra-Concentrado 60ml,1,VENDA,4,"1,228.52",Fevereiro,2026-02-28
106660,NaT,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021534,Hard Seltzer Limão 310ml,1,VENDA,9,"1,480.32",Fevereiro,2026-02-28
106661,NaT,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,"1,553.94",Fevereiro,2026-02-28
106662,NaT,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,"1,845.10",Fevereiro,2026-02-28
106663,NaT,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88,Fevereiro,2026-02-28

In [36]:
base_vendas_periodo.shape

(106664, 13)

## 5. Padrozinando os campos antes de concatenar

In [37]:
base_venda_dezembro = base_venda_dezembro.rename(columns={
    "DATA": "DATAEMISSAO"
})

In [38]:
base_vendas_periodo = pd.concat([
    base_venda_dezembro, 
    base_venda_janeiro, 
    base_venda_fevereiro
], ignore_index=True)

## 6. Verificando o resultado

In [39]:
base_vendas_periodo

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,MES
0,2025-12-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,1,VENDA,1315,"7,311.40",Dezembro
1,2025-12-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013060,Bebidas Prontas para Consumo (RTD),10005769,Pack 4 Unidades Gin Tônica 269ml,1,VENDA,730,"4,015.00",Dezembro
2,2025-12-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015857,Drink Misto Peach 269ml,1,VENDA,2000,"28,440.00",Dezembro
3,2025-12-01,10001683,ATACADISTA BRINDE AMIGO,90013060,Bebidas Prontas para Consumo (RTD),10005769,Pack 4 Unidades Gin Tônica 269ml,1,VENDA,26,377.26,Dezembro
4,2025-12-01,10004002,COMERCIAL MUNDO DAS BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015849,Drink Misto Blueberry 330ml,3,BONIFICAÇÃO,15,55.05,Dezembro
...,...,...,...,...,...,...,...,...,...,...,...,...
106659,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503405,Energéticos de Alta Performance,10023656,Shot Energético Ultra-Concentrado 60ml,1,VENDA,4,"1,228.52",Fevereiro
106660,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021534,Hard Seltzer Limão 310ml,1,VENDA,9,"1,480.32",Fevereiro
106661,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,"1,553.94",Fevereiro
106662,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,"1,845.10",Fevereiro
106663,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88,Fevereiro

In [40]:
base_vendas_periodo.shape

(106664, 12)

In [41]:
base_vendas_periodo.to_csv(r"C:\Users\Joao.Maria\Documents\Analise\Base\Base de Vendas Dez, Jan, Fev.csv", sep=";", index=False)

## 7. Boas práticas
- Garantir mesmas colunas
- Criar coluna de rastreabilidade
- Usar ignore_index=True
- Validar dados após concat
- Evitar concat em loops

## 8. Pivot

Agora vamos transformar a base consolidada em uma tabela analítica, facilitando a leitura dos dados.

### Pivot por Mês

Quanto foi faturado em cada mês?

In [42]:
pivot_mes = base_vendas_periodo.pivot_table(
    values="VALORLIQUIDO",
    index="MES",
    aggfunc="sum"
)

display(pivot_mes)

            VALORLIQUIDO
MES
Dezembro  349,553,210.03
Fevereiro 127,422,295.10
Janeiro   409,820,546.79

### Por Mês e Tipo Faturamento

Como o faturamento se distribui por tipo?

In [43]:
pivot_faturamento = base_vendas_periodo.pivot_table(
    values="VALORLIQUIDO",
    index="MES",
    columns="TIPOFATURAMENTO",
    aggfunc="sum",
    fill_value=0
)

pivot_faturamento

TIPOFATURAMENTO,1,2,3,13,14
MES,,,,,
Dezembro,"341,988,461.42","-1,254,101.19","130,184.58","8,703,998.45","-15,333.23"
Fevereiro,"103,395,853.13","-708,379.74","1,877,937.68","22,748,451.17","108,432.86"
Janeiro,"401,256,922.63","-1,398,739.23","154,337.58","9,826,964.93","-18,939.12"

### Faturamento por familia de produto e mês

Como o faturamento se distribui por tipo?

In [44]:
pivot_grupo = base_vendas_periodo.pivot_table(
    values="VALORLIQUIDO",
    index="DESCRICAOGRUPOPRODUTO",
    columns="MES",
    aggfunc="sum",
    fill_value=0
)

pivot_grupo

MES,Dezembro,Fevereiro,Janeiro
DESCRICAOGRUPOPRODUTO,,,
Base para Bebidas Alcoólicas,"39,473.53","1,963.05","125,592.09"
Bebidas Energéticas Funcionais,"25,910,203.13","4,040,350.56","30,730,991.68"
Bebidas Energéticas Premium,"22,141,232.01","4,853,774.76","25,901,541.52"
Bebidas Funcionais Naturais,"93,083.08","2,850.95","70,964.32"
Bebidas Funcionais Vitaminadas,"15,397,990.26","4,805,289.85","17,792,760.73"
Bebidas Gasosas Saborizadas,"22,500,259.54","2,241,998.95","27,390,970.06"
Bebidas Ice e Cooler,"2,909,284.12","2,124,308.88","2,878,772.79"
Bebidas Mistas Alcoólicas,"82,400,597.39","60,145,298.54","96,157,237.74"
Bebidas Nutricionais,"109,241.51",673.77,"95,555.22"
Bebidas Prontas Geladas,"17,029,031.04","1,842,549.62","20,288,164.96"
Bebidas Prontas para Consumo (RTD),"34,001,361.71","4,374,827.90","39,868,158.70"
Bebidas Relaxantes e Digestivas,"163,093.36","1,453.28","105,779.22"
Categoria de Bebidas Diversas,"1,041,570.32","7,592.89","1,102,299.67"
Cervejas Artesanais Lupuladas,"11,743,176.02","4,241,202.22","13,971,819.31"
Cervejas Artesanais Premium,"6,176,599.66","4,917,591.71","7,520,004.45"
Cervejas Comerciais,"182,548.34","2,801.50","126,637.54"
Cervejas Especiais de Produção,"83,897.18","1,457.34","102,772.99"
Cervejas Especiais de Trigo,"9,433,773.11","718,797.65","10,270,918.02"
Cervejas Industriais,"161,950.43","5,899.41","188,085.66"
Cervejas Industriais Premium,"96,525.85","1,711.39","132,422.67"
Cervejas Lager Tradicionais,"5,993,502.77","1,910,719.60","6,690,827.81"
Cervejas Premium de Mercado,"8,113.40",318.00,"16,224.00"
Cervejas Puro Malte,"8,376,769.13","13,800,420.58","9,442,884.25"
Cervejas Regionais,"5,554,505.24","1,377,180.01","6,271,697.34"
Cervejas de Grande Produção,"100,012.61","2,261.56","116,898.42"
Controle de Qualidade de Bebidas,"1,750,496.02","680,409.65","1,940,460.12"
Destilados Clássicos,"3,437,853.88","650,224.26","3,828,082.42"
Destilados Envelhecidos,"1,953,698.60","254,186.13","2,474,134.14"
Destilados Especiais,"3,575,813.70","652,124.04","4,194,819.40"
Destilados Premium,"6,570,165.99","2,659,529.01","7,971,442.02"
Destilados Ultra Premium,0.00,161.02,"10,307.95"
Destilados de Alta Graduação,"67,497.72","7,428.90","63,617.38"
Energéticos de Alta Performance,"3,379,205.40","766,463.54","4,263,432.86"
Equipamentos para Produção de Bebidas,"852,703.63","21,049.61","868,051.05"
Espumantes e Vinhos Finos,"13,134.68","2,164.77","34,370.02"
Insumos para Produção de Bebidas,"5,793,962.31","2,077,461.06","7,324,812.76"
Laboratório de Qualidade de Bebidas,"95,296.84","18,038.16","25,320.55"
Licores e Destilados Aromáticos,"9,434.88",52.92,"32,472.84"
Matéria-prima para Bebidas,"114,566.25","14,071.45","69,390.13"
Produção de Bebidas em Escala,"141,088.23","1,854.53","137,806.11"
Produção de Bebidas em Grande Escala,"2,298,354.74","582,369.34","2,600,119.36"
Refrigerantes Premium,"11,395.44",162.20,"48,701.19"
Refrigerantes Sabor Cola,"11,295,098.71","568,012.38","13,387,408.72"
Refrigerantes Sabor Frutas,"3,522,442.84","259,390.21","4,242,495.46"
Refrigerantes Tradicionais,"1,379,910.65","78,709.76","1,115,623.30"
Sucos Naturais Premium,"20,198,977.41","3,366,567.61","23,637,785.49"
Vinhos Tintos Importados,"11,316,748.22","3,331,726.47","14,075,851.30"
Vinhos e Espumantes,"127,569.15","6,844.11","114,061.06"

### Sem ordenação, a tabela fica inútil.

In [45]:
pivot_grupo = pivot_grupo.sort_values(
    by="Fevereiro",
    ascending=False
)

pivot_grupo

MES,Dezembro,Fevereiro,Janeiro
DESCRICAOGRUPOPRODUTO,,,
Bebidas Mistas Alcoólicas,"82,400,597.39","60,145,298.54","96,157,237.74"
Cervejas Puro Malte,"8,376,769.13","13,800,420.58","9,442,884.25"
Cervejas Artesanais Premium,"6,176,599.66","4,917,591.71","7,520,004.45"
Bebidas Energéticas Premium,"22,141,232.01","4,853,774.76","25,901,541.52"
Bebidas Funcionais Vitaminadas,"15,397,990.26","4,805,289.85","17,792,760.73"
Bebidas Prontas para Consumo (RTD),"34,001,361.71","4,374,827.90","39,868,158.70"
Cervejas Artesanais Lupuladas,"11,743,176.02","4,241,202.22","13,971,819.31"
Bebidas Energéticas Funcionais,"25,910,203.13","4,040,350.56","30,730,991.68"
Sucos Naturais Premium,"20,198,977.41","3,366,567.61","23,637,785.49"
Vinhos Tintos Importados,"11,316,748.22","3,331,726.47","14,075,851.30"
Destilados Premium,"6,570,165.99","2,659,529.01","7,971,442.02"
Bebidas Gasosas Saborizadas,"22,500,259.54","2,241,998.95","27,390,970.06"
Bebidas Ice e Cooler,"2,909,284.12","2,124,308.88","2,878,772.79"
Insumos para Produção de Bebidas,"5,793,962.31","2,077,461.06","7,324,812.76"
Cervejas Lager Tradicionais,"5,993,502.77","1,910,719.60","6,690,827.81"
Bebidas Prontas Geladas,"17,029,031.04","1,842,549.62","20,288,164.96"
Cervejas Regionais,"5,554,505.24","1,377,180.01","6,271,697.34"
Energéticos de Alta Performance,"3,379,205.40","766,463.54","4,263,432.86"
Cervejas Especiais de Trigo,"9,433,773.11","718,797.65","10,270,918.02"
Controle de Qualidade de Bebidas,"1,750,496.02","680,409.65","1,940,460.12"
Destilados Especiais,"3,575,813.70","652,124.04","4,194,819.40"
Destilados Clássicos,"3,437,853.88","650,224.26","3,828,082.42"
Produção de Bebidas em Grande Escala,"2,298,354.74","582,369.34","2,600,119.36"
Refrigerantes Sabor Cola,"11,295,098.71","568,012.38","13,387,408.72"
Refrigerantes Sabor Frutas,"3,522,442.84","259,390.21","4,242,495.46"
Destilados Envelhecidos,"1,953,698.60","254,186.13","2,474,134.14"
Refrigerantes Tradicionais,"1,379,910.65","78,709.76","1,115,623.30"
Equipamentos para Produção de Bebidas,"852,703.63","21,049.61","868,051.05"
Laboratório de Qualidade de Bebidas,"95,296.84","18,038.16","25,320.55"
Matéria-prima para Bebidas,"114,566.25","14,071.45","69,390.13"
Categoria de Bebidas Diversas,"1,041,570.32","7,592.89","1,102,299.67"
Destilados de Alta Graduação,"67,497.72","7,428.90","63,617.38"
Vinhos e Espumantes,"127,569.15","6,844.11","114,061.06"
Cervejas Industriais,"161,950.43","5,899.41","188,085.66"
Bebidas Funcionais Naturais,"93,083.08","2,850.95","70,964.32"
Cervejas Comerciais,"182,548.34","2,801.50","126,637.54"
Cervejas de Grande Produção,"100,012.61","2,261.56","116,898.42"
Espumantes e Vinhos Finos,"13,134.68","2,164.77","34,370.02"
Base para Bebidas Alcoólicas,"39,473.53","1,963.05","125,592.09"
Produção de Bebidas em Escala,"141,088.23","1,854.53","137,806.11"
Cervejas Industriais Premium,"96,525.85","1,711.39","132,422.67"
Cervejas Especiais de Produção,"83,897.18","1,457.34","102,772.99"
Bebidas Relaxantes e Digestivas,"163,093.36","1,453.28","105,779.22"
Bebidas Nutricionais,"109,241.51",673.77,"95,555.22"
Cervejas Premium de Mercado,"8,113.40",318.00,"16,224.00"
Refrigerantes Premium,"11,395.44",162.20,"48,701.19"
Destilados Ultra Premium,0.00,161.02,"10,307.95"
Licores e Destilados Aromáticos,"9,434.88",52.92,"32,472.84"

### Múltiplas métricas

In [46]:
pivot_multi = base_vendas_periodo.pivot_table(
    values=["VALORLIQUIDO", "VOLUME"],
    index="MES",
    aggfunc="sum"
)

pivot_multi

            VALORLIQUIDO    VOLUME
MES
Dezembro  349,553,210.03  27967966
Fevereiro 127,422,295.10   1267688
Janeiro   409,820,546.79  32713671