# Aula 04 – Transformação de Dados

## Objetivo da aula

Nesta aula vamos aprender como transformar dados no **Pandas**, criando novas colunas, ajustando nomes, tratando textos e trabalhando com datas.

Você irá aprender:

- Criação de colunas derivadas
- Uso de **assign()**
- Uso de **rename()**
- Uso de **map()**
- Uso consciente de **apply()**
- Manipulação de strings
- Conversão e manipulação de datas

# 1. Importando o Pandas

Vamos começar importando a biblioteca **Pandas**.

In [48]:
import pandas as pd
import numpy as np

# 2. Lendo a base de dados

Ajuste o código abaixo com o caminho e a forma de leitura da sua base.

In [49]:
arquivo = r"C:\Users\Joao.Maria\Documents\curso-python_joao_pedro\Base\Base_analitica_vendas.xlsx"

base_vendas = pd.read_excel(arquivo, sheet_name="Base")

# 3. Visualizando a base

Antes de transformar os dados, vamos observar a estrutura inicial.

In [50]:
base_vendas.head()

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07

# 4. Criação de colunas derivadas

Colunas derivadas são criadas a partir de colunas que já existem na base.

### Exemplo: valor por unidade

In [51]:
base_vendas["VALOR UNITARIO"] = base_vendas["VALORLIQUIDO"] / base_vendas["VOLUME"]

base_vendas[["NOMEPRODUTO", "VOLUME", "VALORLIQUIDO", "VALOR UNITARIO"]].head()

                           NOMEPRODUTO  VOLUME  VALORLIQUIDO  VALOR UNITARIO
0       Isotônico Uva Vitaminado 500ml       3        472.41        157.4700
1  Cerveja Lager Standard 350ml (Lata)      50       1973.87         39.4774
2       Suco de Laranja Integral 500ml       5        444.46         88.8920
3             Néctar de Uva Premium 1L       1        397.90        397.9000
4  Lúpulo em Pellet para Brassagem 5kg     100       1304.07         13.0407

### Exemplo: cópia de uma coluna com outro significado de análise

In [52]:
base_vendas["CLIENTE"] = base_vendas["DESCRICAOCLIENTE"]

base_vendas[["DESCRICAOCLIENTE", "CLIENTE"]].head()

       DESCRICAOCLIENTE               CLIENTE
0  ATACADO BRINDE & CIA  ATACADO BRINDE & CIA
1  ATACADO BRINDE & CIA  ATACADO BRINDE & CIA
2  ATACADO BRINDE & CIA  ATACADO BRINDE & CIA
3  ATACADO BRINDE & CIA  ATACADO BRINDE & CIA
4  ATACADO BRINDE & CIA  ATACADO BRINDE & CIA

# 5. Usando assign()

O **assign()** permite criar colunas novas de forma organizada.

In [53]:
base_vendas = base_vendas.assign(
    VALOR_DOBRADO = base_vendas["VALORLIQUIDO"] * 2,
    VOLUME_DOBRADO = base_vendas["VOLUME"] * 2
)

base_vendas[["VALORLIQUIDO", "VALOR_DOBRADO", "VOLUME", "VOLUME_DOBRADO"]].head()

   VALORLIQUIDO  VALOR_DOBRADO  VOLUME  VOLUME_DOBRADO
0        472.41         944.82       3               6
1       1973.87        3947.74      50             100
2        444.46         888.92       5              10
3        397.90         795.80       1               2
4       1304.07        2608.14     100             200

# 6. Usando rename()

O **rename()** serve para renomear colunas da base.

In [54]:
base_renomeada = base_vendas.rename(columns={
    "DATAEMISSAO": "DATA VENDA",
    "VALORLIQUIDO": "VALOR TOTAL LIQUIDO"
})

base_renomeada.head()

,DATA VENDA,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALOR TOTAL LIQUIDO,VALOR UNITARIO,CLIENTE,VALOR_DOBRADO,VOLUME_DOBRADO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41,157.4700,ATACADO BRINDE & CIA,944.82,6
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87,39.4774,ATACADO BRINDE & CIA,3947.74,100
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46,88.8920,ATACADO BRINDE & CIA,888.92,10
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90,397.9000,ATACADO BRINDE & CIA,795.80,2
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07,13.0407,ATACADO BRINDE & CIA,2608.14,200

# 7. Usando map()

O **map()** é útil para traduzir ou classificar valores de uma coluna.

In [55]:
base_vendas[["TIPOFATURAMENTO", "DESCRICAOTIPOFATURAMENTO"]].drop_duplicates()

     TIPOFATURAMENTO DESCRICAOTIPOFATURAMENTO
0                  1                    VENDA
29                 3              BONIFICAÇÃO
372                2       DEVOLUÇÃO DE VENDA
470               14      DEVOLUÇÃO DE COMPRA
558               13                   COMPRA

In [56]:
mapa_faturamento = {
    1: "Operação Comercial",
    2: "Ajuste de inventário",
    3: "Cortesia/Amostra",
    13: "Operação Comercial",
    14: "Ajuste de inventário",
   
}

base_vendas["TIPO OPERACAO"] = base_vendas["TIPOFATURAMENTO"].map(mapa_faturamento)

base_vendas[["TIPOFATURAMENTO", "TIPO OPERACAO"]].drop_duplicates()

     TIPOFATURAMENTO         TIPO OPERACAO
0                  1    Operação Comercial
29                 3      Cortesia/Amostra
372                2  Ajuste de inventário
470               14  Ajuste de inventário
558               13    Operação Comercial

Se algum valor não estiver no dicionário, o resultado será **NaN**.

# 8. Usando apply() com consciência

O **apply()** é útil em casos mais personalizados, mas deve ser usado com cuidado.

Em muitas situações, operações diretas e vetorizadas são melhores.

In [57]:
def classificar_valor(valor):
    if valor >= 1000:
        return "Alto"
    else:
        return "Baixo"

base_vendas["FAIXA_VALOR"] = base_vendas["VALORLIQUIDO"].apply(classificar_valor)

base_vendas[["VALORLIQUIDO", "FAIXA_VALOR"]].head(10)

   VALORLIQUIDO FAIXA_VALOR
0        472.41       Baixo
1       1973.87        Alto
2        444.46       Baixo
3        397.90       Baixo
4       1304.07        Alto
5        383.31       Baixo
6       1261.78        Alto
7        176.22       Baixo
8         76.71       Baixo
9        229.87       Baixo

# 9. Criando colunas com condições, utilizando o NumPy

A biblioteca **NumPy** é perfeita para calculos, e bastante performática quando se trata de muitos dados, geralmente é melhor pratica do que usar o **.apply()**

Em muitas situações, operações diretas e vetorizadas são melhores.

#### **np.where** é basicamente um if e else da biblioteca

In [58]:
base_vendas["CLASSIFICACAO VALOR"] = np.where(
    base_vendas["VALORLIQUIDO"] >= 1000, 
    "Alto", 
    "Baixo"
)

base_vendas[["VALORLIQUIDO", "FAIXA_VALOR", "CLASSIFICACAO VALOR"]].head(10)

   VALORLIQUIDO FAIXA_VALOR CLASSIFICACAO VALOR
0        472.41       Baixo               Baixo
1       1973.87        Alto                Alto
2        444.46       Baixo               Baixo
3        397.90       Baixo               Baixo
4       1304.07        Alto                Alto
5        383.31       Baixo               Baixo
6       1261.78        Alto                Alto
7        176.22       Baixo               Baixo
8         76.71       Baixo               Baixo
9        229.87       Baixo               Baixo

#### **np.select** conseguimos trabalhar com diversas condições

In [59]:
base_vendas["CLASSIFICACAO VALOR COM CONDICOES"] = np.select(
    [
        base_vendas["VALORLIQUIDO"] >= 1000, 
        (base_vendas["VALORLIQUIDO"] < 1000) & (base_vendas["VALORLIQUIDO"] >= 500),
        base_vendas["VALORLIQUIDO"] < 500
    ], 
    [
        "Alto", 
        "Médio", 
        "Baixo"
    ],
    default="Desconecido"
)

base_vendas[["VALORLIQUIDO", "FAIXA_VALOR", "CLASSIFICACAO VALOR", "CLASSIFICACAO VALOR COM CONDICOES"]].head(10)

,VALORLIQUIDO,FAIXA_VALOR,CLASSIFICACAO VALOR,CLASSIFICACAO VALOR COM CONDICOES
0,472.41,Baixo,Baixo,Baixo
1,1973.87,Alto,Alto,Alto
2,444.46,Baixo,Baixo,Baixo
3,397.90,Baixo,Baixo,Baixo
4,1304.07,Alto,Alto,Alto
5,383.31,Baixo,Baixo,Baixo
6,1261.78,Alto,Alto,Alto
7,176.22,Baixo,Baixo,Baixo
8,76.71,Baixo,Baixo,Baixo
9,229.87,Baixo,Baixo,Baixo

# 10. Manipulação de strings

As funções de string ajudam a padronizar e extrair partes de textos.

### Transformando nome do produto em maiúsculo

In [60]:
base_vendas["NOMEPRODUTO MAIUSCULO"] = base_vendas["NOMEPRODUTO"].str.upper()

base_vendas[["NOMEPRODUTO", "NOMEPRODUTO MAIUSCULO"]].head()

                           NOMEPRODUTO                NOMEPRODUTO MAIUSCULO
0       Isotônico Uva Vitaminado 500ml       ISOTÔNICO UVA VITAMINADO 500ML
1  Cerveja Lager Standard 350ml (Lata)  CERVEJA LAGER STANDARD 350ML (LATA)
2       Suco de Laranja Integral 500ml       SUCO DE LARANJA INTEGRAL 500ML
3             Néctar de Uva Premium 1L             NÉCTAR DE UVA PREMIUM 1L
4  Lúpulo em Pellet para Brassagem 5kg  LÚPULO EM PELLET PARA BRASSAGEM 5KG

### Extraindo a primeira palavra do nome do produto

In [61]:
base_vendas["PRIMEIRA_PALAVRA_PRODUTO"] = base_vendas["NOMEPRODUTO"].str.split().str[0]

base_vendas[["NOMEPRODUTO", "PRIMEIRA_PALAVRA_PRODUTO"]].head()

                           NOMEPRODUTO PRIMEIRA_PALAVRA_PRODUTO
0       Isotônico Uva Vitaminado 500ml                Isotônico
1  Cerveja Lager Standard 350ml (Lata)                  Cerveja
2       Suco de Laranja Integral 500ml                     Suco
3             Néctar de Uva Premium 1L                   Néctar
4  Lúpulo em Pellet para Brassagem 5kg                   Lúpulo

# 11. Conversão de datas

Antes de trabalhar com datas, precisamos garantir que a coluna está no tipo correto.

In [62]:
base_vendas["DATAEMISSAO"] = pd.to_datetime(base_vendas["DATAEMISSAO"])

base_vendas[["DATAEMISSAO"]]

      DATAEMISSAO
0      2026-02-01
1      2026-02-01
2      2026-02-01
3      2026-02-01
4      2026-02-01
...           ...
40616  2026-02-28
40617  2026-02-28
40618  2026-02-28
40619  2026-02-28
40620  2026-02-28

[40621 rows x 1 columns]

In [63]:
base_vendas["DATAEMISSAO"].dtype

dtype('<M8[us]')

# 12. Manipulação de datas

Depois da conversão, podemos extrair partes da data.

### Criando colunas de ano, mês e dia

In [64]:
base_vendas["ANO"] = base_vendas["DATAEMISSAO"].dt.year
base_vendas["MES"] = base_vendas["DATAEMISSAO"].dt.month
base_vendas["DIA"] = base_vendas["DATAEMISSAO"].dt.day

base_vendas[["DATAEMISSAO", "ANO", "MES", "DIA"]].head()

  DATAEMISSAO   ANO  MES  DIA
0  2026-02-01  2026    2    1
1  2026-02-01  2026    2    1
2  2026-02-01  2026    2    1
3  2026-02-01  2026    2    1
4  2026-02-01  2026    2    1

### Criando o nome do dia da semana

In [65]:
base_vendas["DIA_SEMANA"] = base_vendas["DATAEMISSAO"].dt.day_name()

base_vendas[["DATAEMISSAO", "DIA_SEMANA"]].head()

  DATAEMISSAO DIA_SEMANA
0  2026-02-01     Sunday
1  2026-02-01     Sunday
2  2026-02-01     Sunday
3  2026-02-01     Sunday
4  2026-02-01     Sunday

### Criando o nome do dia da semana em português

In [66]:
base_vendas["DIA_SEMANA"] = base_vendas["DATAEMISSAO"].dt.day_name(locale="pt_BR")

base_vendas[["DATAEMISSAO", "DIA_SEMANA"]].sample(5)

      DATAEMISSAO    DIA_SEMANA
4620   2026-02-04  Quarta-feira
14699  2026-02-11  Quarta-feira
6791   2026-02-06   Sexta-feira
34855  2026-02-24   Terça-feira
24977  2026-02-17   Terça-feira

### Criando uma coluna no formato ano-mês

In [67]:
base_vendas["ANO_MES"] = base_vendas["DATAEMISSAO"].dt.strftime("%Y-%m")

base_vendas[["DATAEMISSAO", "ANO_MES"]].head()

  DATAEMISSAO  ANO_MES
0  2026-02-01  2026-02
1  2026-02-01  2026-02
2  2026-02-01  2026-02
3  2026-02-01  2026-02
4  2026-02-01  2026-02

# 13. Resultado final

Agora a base possui novas colunas geradas a partir das transformações.

In [68]:
base_vendas.head(5)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,...,FAIXA_VALOR,CLASSIFICACAO VALOR,CLASSIFICACAO VALOR COM CONDICOES,NOMEPRODUTO MAIUSCULO,PRIMEIRA_PALAVRA_PRODUTO,ANO,MES,DIA,DIA_SEMANA,ANO_MES
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,...,Baixo,Baixo,Baixo,ISOTÔNICO UVA VITAMINADO 500ML,Isotônico,2026,2,1,Domingo,2026-02
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,...,Alto,Alto,Alto,CERVEJA LAGER STANDARD 350ML (LATA),Cerveja,2026,2,1,Domingo,2026-02
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,...,Baixo,Baixo,Baixo,SUCO DE LARANJA INTEGRAL 500ML,Suco,2026,2,1,Domingo,2026-02
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,...,Baixo,Baixo,Baixo,NÉCTAR DE UVA PREMIUM 1L,Néctar,2026,2,1,Domingo,2026-02
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,...,Alto,Alto,Alto,LÚPULO EM PELLET PARA BRASSAGEM 5KG,Lúpulo,2026,2,1,Domingo,2026-02