# Aula 03 – Limpeza e Qualidade de Dados

## Objetivo da aula

Nesta aula vamos aprender como tratar dados para garantir qualidade na análise.

**Você irá aprender:**
- copy()
- isna()
- fillna()
- dropna()
- duplicated()
- drop_duplicates()
- Padronização de strings
- Conversão de tipos
- Remoção de colunas desnecessárias

## 1. Importando o Pandas

In [11]:
import pandas as pd

## 2. Lendo a base de dados

In [12]:
arquivo = r"C:\Users\Joao.Maria\Documents\curso-python_joao_pedro\Base\Base venda bruta marco.csv"
base_vendas = pd.read_csv(arquivo, sep=";")

## 3. Visualizando a base

In [13]:
base_vendas.head()

,DATA,UF,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,VOLUMESELLOUT,PRECO,DATACARGA
0,2026-03-07,RJ,91503409,Bebidas Prontas Geladas,10021539,Hard Seltzer Guaraná 310ml,10.0,15.00,2026-04-01
1,2026-03-16,PR,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,50.0,15.00,2026-04-01
2,2026-03-26,MG,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,NaN,10.50,2026-04-01
3,2026-03-22,PR,90013211,Controle de Qualidade de Bebidas,10022262,Solução de Limpeza Sanitizante 5L,NaN,10.50,2026-04-01
4,2026-03-26,BA,90013060,Bebidas Prontas para Consumo (RTD),10005773,Gin Tônica 1L (Garrafa),10.0,5.99,2026-04-01

In [14]:
base_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   DATA                   505 non-null    str
 1   UF                     455 non-null    str
 2   CODIGOGRUPOPRODUTO     520 non-null    int64
 3   DESCRICAOGRUPOPRODUTO  520 non-null    str
 4   CODIGOPRODUTO          520 non-null    int64
 5   NOMEPRODUTO            520 non-null    str
 6   VOLUMESELLOUT          383 non-null    float64
 7   PRECO                  520 non-null    float64
 8   DATACARGA              520 non-null    str
dtypes: float64(2), int64(2), str(5)
memory usage: 36.7 KB

## 4. Criando uma cópia da base

In [15]:
base_vendas_tratado = base_vendas.copy()

## 5. Identificando valores nulos

In [16]:
base_vendas_tratado.isna().sum()

DATA                      15
UF                        65
CODIGOGRUPOPRODUTO         0
DESCRICAOGRUPOPRODUTO      0
CODIGOPRODUTO              0
NOMEPRODUTO                0
VOLUMESELLOUT            137
PRECO                      0
DATACARGA                  0
dtype: int64

## 6. Tratando valores nulos

In [17]:
base_vendas_tratado["VOLUMESELLOUT"] = base_vendas_tratado["VOLUMESELLOUT"].fillna(0)

base_vendas_tratado[["VOLUMESELLOUT"]].sample(6)

     VOLUMESELLOUT
331           20.0
61             0.0
228            0.0
64            50.0
17            10.0
2              0.0

In [18]:
base_vendas_tratado["UF"] = base_vendas_tratado["UF"].fillna("DESCONHECIDO")

base_vendas_tratado[["UF"]].sample(6)

               UF
15             MG
317  DESCONHECIDO
453  DESCONHECIDO
401            BA
268            PR
23             BA

## 7. Removendo registros inválidos

In [19]:
base_vendas_tratado = base_vendas_tratado.dropna(subset=["DATA"])

base_vendas_tratado[["DATA"]].isnull().sum()

DATA    0
dtype: int64

## 8. Verificando duplicidade

In [20]:
base_vendas_tratado.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
515     True
516     True
517     True
518     True
519     True
Length: 505, dtype: bool

## 9. Removendo duplicados

In [21]:
base_vendas_tratado = base_vendas_tratado.drop_duplicates()

base_vendas_tratado.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 486, dtype: bool

## 10. Padronização de strings

In [22]:
base_vendas_tratado["UF"] = base_vendas_tratado["UF"].str.strip().str.upper()

base_vendas_tratado["UF"].sample(6)

401              BA
183              BA
237              SP
187    DESCONHECIDO
76               PR
296              RJ
Name: UF, dtype: str

In [23]:
base_vendas_tratado["NOMEPRODUTO"] = base_vendas_tratado["NOMEPRODUTO"].str.strip()

base_vendas_tratado.head(3)

,DATA,UF,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,VOLUMESELLOUT,PRECO,DATACARGA
0,2026-03-07,RJ,91503409,Bebidas Prontas Geladas,10021539,Hard Seltzer Guaraná 310ml,10.0,15.0,2026-04-01
1,2026-03-16,PR,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,50.0,15.0,2026-04-01
2,2026-03-26,MG,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,0.0,10.5,2026-04-01

## 11. Conversão de tipos

In [24]:
base_vendas_tratado["DATA"] = pd.to_datetime(base_vendas_tratado["DATA"])

base_vendas_tratado.info()

<class 'pandas.DataFrame'>
Index: 486 entries, 0 to 499
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   DATA                   486 non-null    datetime64[us]
 1   UF                     486 non-null    str
 2   CODIGOGRUPOPRODUTO     486 non-null    int64
 3   DESCRICAOGRUPOPRODUTO  486 non-null    str
 4   CODIGOPRODUTO          486 non-null    int64
 5   NOMEPRODUTO            486 non-null    str
 6   VOLUMESELLOUT          486 non-null    float64
 7   PRECO                  486 non-null    float64
 8   DATACARGA              486 non-null    str
dtypes: datetime64[us](1), float64(2), int64(2), str(4)
memory usage: 38.0 KB

In [25]:
base_vendas_tratado["PRECO"] = base_vendas_tratado["PRECO"].astype(float)

base_vendas_tratado.info()

<class 'pandas.DataFrame'>
Index: 486 entries, 0 to 499
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   DATA                   486 non-null    datetime64[us]
 1   UF                     486 non-null    str
 2   CODIGOGRUPOPRODUTO     486 non-null    int64
 3   DESCRICAOGRUPOPRODUTO  486 non-null    str
 4   CODIGOPRODUTO          486 non-null    int64
 5   NOMEPRODUTO            486 non-null    str
 6   VOLUMESELLOUT          486 non-null    float64
 7   PRECO                  486 non-null    float64
 8   DATACARGA              486 non-null    str
dtypes: datetime64[us](1), float64(2), int64(2), str(4)
memory usage: 38.0 KB

## 12. Removendo coluna desnecessária

In [26]:
base_vendas_tratado = base_vendas_tratado.drop(columns=["DATACARGA"])

## 13. Conferindo resultado final

In [27]:
base_vendas_tratado.head()

,DATA,UF,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,VOLUMESELLOUT,PRECO
0,2026-03-07,RJ,91503409,Bebidas Prontas Geladas,10021539,Hard Seltzer Guaraná 310ml,10.0,15.00
1,2026-03-16,PR,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,50.0,15.00
2,2026-03-26,MG,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,0.0,10.50
3,2026-03-22,PR,90013211,Controle de Qualidade de Bebidas,10022262,Solução de Limpeza Sanitizante 5L,0.0,10.50
4,2026-03-26,BA,90013060,Bebidas Prontas para Consumo (RTD),10005773,Gin Tônica 1L (Garrafa),10.0,5.99

In [28]:
base_vendas_tratado.info()

<class 'pandas.DataFrame'>
Index: 486 entries, 0 to 499
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   DATA                   486 non-null    datetime64[us]
 1   UF                     486 non-null    str
 2   CODIGOGRUPOPRODUTO     486 non-null    int64
 3   DESCRICAOGRUPOPRODUTO  486 non-null    str
 4   CODIGOPRODUTO          486 non-null    int64
 5   NOMEPRODUTO            486 non-null    str
 6   VOLUMESELLOUT          486 non-null    float64
 7   PRECO                  486 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(2), str(3)
memory usage: 34.2 KB

## 14. Aplicação prática

In [35]:
base_vendas_tratado.groupby(["UF", "DESCRICAOGRUPOPRODUTO"])["VOLUMESELLOUT"].sum().sort_values(ascending=False).reset_index().head(5)

   UF               DESCRICAOGRUPOPRODUTO  VOLUMESELLOUT
0  SP  Bebidas Prontas para Consumo (RTD)          440.0
1  RJ           Bebidas Mistas Alcoólicas          420.0
2  RJ  Bebidas Prontas para Consumo (RTD)          280.0
3  PR           Bebidas Mistas Alcoólicas          230.0
4  SP           Bebidas Mistas Alcoólicas          210.0

In [37]:
base_vendas.to_excel("teste2.xlsx")

In [34]:
base_vendas.groupby(["UF", "DESCRICAOGRUPOPRODUTO"])["VOLUMESELLOUT"].sum().sort_values(ascending=False).reset_index().head(5)

    UF               DESCRICAOGRUPOPRODUTO  VOLUMESELLOUT
0   RJ           Bebidas Mistas Alcoólicas          360.0
1  sp   Bebidas Prontas para Consumo (RTD)          270.0
2   PR           Bebidas Mistas Alcoólicas          230.0
3   SP  Bebidas Prontas para Consumo (RTD)          220.0
4   SP           Bebidas Mistas Alcoólicas          180.0

In [31]:
base_vendas_tratado.to_csv("Base tratada.csv", sep=";", index=False)