# Aula 07 – Relacionamento de Dados

## Objetivo
Relacionar base de vendas (fato) com dimensões de cliente e produto usando dados reais.

## 1. Importando bibliotecas

In [1]:
import pandas as pd

## 2. Carregando os dados

In [2]:
caminho_arquivo_base_venda = r"C:\Users\Joao.Maria\Documents\curso-python_joao_pedro\Base\Captura_venda_marco.json"
caminho_configuracao_produto = r"C:\Users\Joao.Maria\Documents\curso-python_joao_pedro\Base\Configuração Produto.xlsx"
caminho_configuracao_cliente = r"C:\Users\Joao.Maria\Documents\curso-python_joao_pedro\Base\Configuração Cliente.xlsx"

In [ ]:
base_venda = pd.read_json(caminho_arquivo_base_venda, orient="records")
configuracao_produto = pd.read_excel(caminho_configuracao_produto, sheet_name="Produto")
configuracao_cliente = pd.read_excel(caminho_configuracao_cliente, sheet_name="Cliente")

## 3. Visualizando as bases

In [4]:
base_venda.head()

,DATAEMISSAO,CODIGOCLIENTE,CODIGOPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
0,2026-03-01T00:00:00.000,10004221,10023656,1,VENDA,1635,19440.15
1,2026-03-01T00:00:00.000,10004238,10001164,1,VENDA,1852,36743.68
2,2026-03-01T00:00:00.000,10004005,10003635,1,VENDA,1684,10272.40
3,2026-03-01T00:00:00.000,10004221,10026840,1,VENDA,69,1255.80
4,2026-03-01T00:00:00.000,10004002,10022282,1,VENDA,845,16773.25

In [5]:
configuracao_produto.head()

,CODIGOFAMILIA,DESCRICAOFAMILIA,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO
0,80000003,Energético,91503402,Bebidas Energéticas Funcionais,10022949,Energético Focus Max 1L (Garrafa)
1,80000001,Cerveja,90013201,Cervejas Artesanais Premium,10001163,Cerveja Artesanal Alpha Gold 600ml
2,80000007,Vinho,90013032,Vinhos Tintos Importados,10001164,Vinho Tinto Cabernet Reservado 750ml
3,80000001,Cerveja,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata)
4,80000002,Refrigerante,90013153,Refrigerantes Sabor Cola,10001864,Refri Cola Original 250ml

In [6]:
configuracao_cliente.head()

,CODIGOCLIENTE,DESCRICAOCLIENTE,CNPJ,CODIGOGRUPOCLIENTE,DESCRICAOGRUPOCLIENTE
0,10004231,DISTRIBUIDORA REINO DAS BEBIDAS,37.582.419/0001-04,2,Distribuidor
1,10004226,LOGÍSTICA CENTRAL DE BEBIDAS,91.604.237/0001-62,2,Distribuidor
2,10004220,ATACADO COPO GELADO,18.773.950/0001-15,2,Distribuidor
3,10004201,SUPRIMENTOS PREMIUM BEVERAGES,52.449.681/0001-89,2,Distribuidor
4,10004210,CENTRAL LOGÍSTICA DAS BEBIDAS,73.601.228/0001-33,2,Distribuidor

## 4. Merge com Cliente (LEFT JOIN)

### Mantém todas as vendas, mesmo sem cliente correspondente.

In [13]:
base = pd.merge(
    base_venda, 
    configuracao_cliente, 
    on='CODIGOCLIENTE', 
    how='left'
)

base.head()

,DATAEMISSAO,CODIGOCLIENTE,CODIGOPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,DESCRICAOCLIENTE,CNPJ,CODIGOGRUPOCLIENTE,DESCRICAOGRUPOCLIENTE
0,2026-03-01T00:00:00.000,10004221,10023656,1,VENDA,1635,19440.15,DISTRIBUIDORA BRINDE & AMIGOS,68.913.227/0001-22,2,Distribuidor
1,2026-03-01T00:00:00.000,10004238,10001164,1,VENDA,1852,36743.68,LOGÍSTICA BEBIDAS DO BRASIL,47.318.775/0001-86,2,Distribuidor
2,2026-03-01T00:00:00.000,10004005,10003635,1,VENDA,1684,10272.40,DISTRIBUIDORA SABOR DAS BEBIDAS,11.908.442/0001-36,2,Distribuidor
3,2026-03-01T00:00:00.000,10004221,10026840,1,VENDA,69,1255.80,DISTRIBUIDORA BRINDE & AMIGOS,68.913.227/0001-22,2,Distribuidor
4,2026-03-01T00:00:00.000,10004002,10022282,1,VENDA,845,16773.25,COMERCIAL MUNDO DAS BEBIDAS,31.662.540/0001-16,2,Distribuidor

#### Tem como também trazer apenas os campos ao qual a gente precisa

In [14]:
base_cliente = pd.merge(
    base_venda, 
    configuracao_cliente[["CODIGOCLIENTE", "DESCRICAOCLIENTE"]], 
    on='CODIGOCLIENTE', 
    how='left'
)

base_cliente.head()

,DATAEMISSAO,CODIGOCLIENTE,CODIGOPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,DESCRICAOCLIENTE
0,2026-03-01T00:00:00.000,10004221,10023656,1,VENDA,1635,19440.15,DISTRIBUIDORA BRINDE & AMIGOS
1,2026-03-01T00:00:00.000,10004238,10001164,1,VENDA,1852,36743.68,LOGÍSTICA BEBIDAS DO BRASIL
2,2026-03-01T00:00:00.000,10004005,10003635,1,VENDA,1684,10272.40,DISTRIBUIDORA SABOR DAS BEBIDAS
3,2026-03-01T00:00:00.000,10004221,10026840,1,VENDA,69,1255.80,DISTRIBUIDORA BRINDE & AMIGOS
4,2026-03-01T00:00:00.000,10004002,10022282,1,VENDA,845,16773.25,COMERCIAL MUNDO DAS BEBIDAS

## 5. Merge com Produto

In [15]:
base = pd.merge(
    base, 
    configuracao_produto[["CODIGOPRODUTO", "NOMEPRODUTO", "DESCRICAOGRUPOPRODUTO", "DESCRICAOFAMILIA"]], 
    on='CODIGOPRODUTO', 
    how='left'
)

base.head()

,DATAEMISSAO,CODIGOCLIENTE,CODIGOPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,DESCRICAOCLIENTE,CNPJ,CODIGOGRUPOCLIENTE,DESCRICAOGRUPOCLIENTE,NOMEPRODUTO,DESCRICAOGRUPOPRODUTO,DESCRICAOFAMILIA
0,2026-03-01T00:00:00.000,10004221,10023656,1,VENDA,1635,19440.15,DISTRIBUIDORA BRINDE & AMIGOS,68.913.227/0001-22,2,Distribuidor,Shot Energético Ultra-Concentrado 60ml,Energéticos de Alta Performance,Energético
1,2026-03-01T00:00:00.000,10004238,10001164,1,VENDA,1852,36743.68,LOGÍSTICA BEBIDAS DO BRASIL,47.318.775/0001-86,2,Distribuidor,Vinho Tinto Cabernet Reservado 750ml,Vinhos Tintos Importados,Vinho
2,2026-03-01T00:00:00.000,10004005,10003635,1,VENDA,1684,10272.40,DISTRIBUIDORA SABOR DAS BEBIDAS,11.908.442/0001-36,2,Distribuidor,Gin Tônica em Lata 269ml,Bebidas Prontas para Consumo (RTD),RTD
3,2026-03-01T00:00:00.000,10004221,10026840,1,VENDA,69,1255.80,DISTRIBUIDORA BRINDE & AMIGOS,68.913.227/0001-22,2,Distribuidor,Cerveja Session IPA Light 355ml,Cervejas Artesanais Lupuladas,Cerveja
4,2026-03-01T00:00:00.000,10004002,10022282,1,VENDA,845,16773.25,COMERCIAL MUNDO DAS BEBIDAS,31.662.540/0001-16,2,Distribuidor,Isotônico Uva Vitaminado 500ml,Bebidas Funcionais Vitaminadas,Energético

## 6. Problema real – Chaves faltantes

In [16]:
base.isnull().sum()

DATAEMISSAO                 0
CODIGOCLIENTE               0
CODIGOPRODUTO               0
TIPOFATURAMENTO             0
DESCRICAOTIPOFATURAMENTO    0
VOLUME                      0
VALORLIQUIDO                0
DESCRICAOCLIENTE            0
CNPJ                        0
CODIGOGRUPOCLIENTE          0
DESCRICAOGRUPOCLIENTE       0
NOMEPRODUTO                 0
DESCRICAOGRUPOPRODUTO       0
DESCRICAOFAMILIA            0
dtype: int64

### Se houver valores nulos em cliente ou produto, o relacionamento falhou.

## 7. Problema crítico – Duplicidade na dimensão

In [17]:
configuracao_cliente['CODIGOCLIENTE'].duplicated().sum()

np.int64(0)

### Se > 0, você vai multiplicar linhas no merge.

👉 Se aumentou, você tem explosão de dados.

## 8. Tipos de Ligação

    how=
* **inner** → Mantém apenas os registros que existem nas duas tabelas
* **left** → Mantém todos os registros da tabela da esquerda e traz correspondências da direita
* **right** → Mantém todos os registros da tabela da direita e traz correspondências da esquerda
* **outer** → Mantém todos os registros de ambas as tabelas, combinando onde houver correspondência

In [ ]:
clientes_faltantes = pd.merge(
    base_venda,
    configuracao_cliente[["CODIGOCLIENTE", "DESCRICAOCLIENTE"]],
    on="CODIGOCLIENTE",
    how="right"
)

,DATAEMISSAO,CODIGOCLIENTE,CODIGOPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,DESCRICAOCLIENTE
0,NaN,10004231,NaN,NaN,NaN,NaN,NaN,DISTRIBUIDORA REINO DAS BEBIDAS
1,2026-03-01T00:00:00.000,10004226,10022283.0,1.0,VENDA,1017.0,16251.66,LOGÍSTICA CENTRAL DE BEBIDAS
2,2026-03-01T00:00:00.000,10004226,10020282.0,1.0,VENDA,200.0,1810.00,LOGÍSTICA CENTRAL DE BEBIDAS
3,2026-03-01T00:00:00.000,10004226,10016993.0,1.0,VENDA,27.0,532.44,LOGÍSTICA CENTRAL DE BEBIDAS
4,2026-03-01T00:00:00.000,10004226,10003736.0,1.0,VENDA,1542.0,24070.62,LOGÍSTICA CENTRAL DE BEBIDAS

### Filtrando apenas os clientes faltantes

In [32]:
clientes_faltantes = clientes_faltantes[clientes_faltantes["DATAEMISSAO"].isnull()]

clientes_faltantes.head()

,DATAEMISSAO,CODIGOCLIENTE,CODIGOPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,DESCRICAOCLIENTE
0,NaN,10004231,NaN,NaN,NaN,NaN,NaN,DISTRIBUIDORA REINO DAS BEBIDAS
645,NaN,10004220,NaN,NaN,NaN,NaN,NaN,ATACADO COPO GELADO
1545,NaN,10004210,NaN,NaN,NaN,NaN,NaN,CENTRAL LOGÍSTICA DAS BEBIDAS
1546,NaN,10004003,NaN,NaN,NaN,NaN,NaN,REDE BRINDE FELIZ DISTRIBUIÇÃO
2592,NaN,10004212,NaN,NaN,NaN,NaN,NaN,DISTRIBUIDORA PORTAL DAS BEBIDAS

### Identificando os valores nulos de ambas as bases

#### indicator=True cria uma coluna:

* left_only -> só existe em vendas
* right_only -> só existe em clientes
* both -> existe nos dois

In [41]:
comparacao = pd.merge(
    base_venda,
    configuracao_cliente[["CODIGOCLIENTE", "DESCRICAOCLIENTE"]],
    on="CODIGOCLIENTE",
    how="outer",
    indicator=True
)

comparacao.head(25)

,DATAEMISSAO,CODIGOCLIENTE,CODIGOPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO,DESCRICAOCLIENTE,_merge
0,NaN,10000449,NaN,NaN,NaN,NaN,NaN,ATACADO BRINDE & CIA,right_only
1,NaN,10000964,NaN,NaN,NaN,NaN,NaN,LOGÍSTICA ESSENCIAL BEBIDAS,right_only
2,NaN,10001683,NaN,NaN,NaN,NaN,NaN,ATACADISTA BRINDE AMIGO,right_only
3,NaN,10004001,NaN,NaN,NaN,NaN,NaN,LOGÍSTICA GARRAFAS & LOG,right_only
4,2026-03-01T00:00:00.000,10004002,10022282.0,1.0,VENDA,845.0,16773.25,COMERCIAL MUNDO DAS BEBIDAS,both
5,2026-03-01T00:00:00.000,10004002,10015849.0,1.0,VENDA,1389.0,14959.53,COMERCIAL MUNDO DAS BEBIDAS,both
6,2026-03-01T00:00:00.000,10004002,10021534.0,1.0,VENDA,693.0,11725.56,COMERCIAL MUNDO DAS BEBIDAS,both
7,2026-03-01T00:00:00.000,10004002,10015850.0,1.0,VENDA,39.0,417.69,COMERCIAL MUNDO DAS BEBIDAS,both
8,2026-03-01T00:00:00.000,10004002,10002818.0,1.0,VENDA,1793.0,34766.27,COMERCIAL MUNDO DAS BEBIDAS,both
9,2026-03-01T00:00:00.000,10004002,10022637.0,1.0,VENDA,1481.0,22570.44,COMERCIAL MUNDO DAS BEBIDAS,both
10,2026-03-01T00:00:00.000,10004002,10022283.0,1.0,VENDA,153.0,921.06,COMERCIAL MUNDO DAS BEBIDAS,both
11,2026-03-01T00:00:00.000,10004002,10022283.0,1.0,VENDA,1484.0,23788.52,COMERCIAL MUNDO DAS BEBIDAS,both
12,2026-03-01T00:00:00.000,10004002,10015849.0,3.0,BONIFICAÇÃO,42.0,193.62,COMERCIAL MUNDO DAS BEBIDAS,both
13,2026-03-01T00:00:00.000,10004002,10022954.0,1.0,VENDA,9.0,100.53,COMERCIAL MUNDO DAS BEBIDAS,both
14,2026-03-01T00:00:00.000,10004002,10015850.0,1.0,VENDA,1422.0,28198.26,COMERCIAL MUNDO DAS BEBIDAS,both
15,2026-03-01T00:00:00.000,10004002,10001864.0,3.0,BONIFICAÇÃO,34.0,156.40,COMERCIAL MUNDO DAS BEBIDAS,both
16,2026-03-01T00:00:00.000,10004002,10008336.0,1.0,VENDA,1581.0,15082.74,COMERCIAL MUNDO DAS BEBIDAS,both
17,2026-03-01T00:00:00.000,10004002,10022282.0,1.0,VENDA,186.0,2099.94,COMERCIAL MUNDO DAS BEBIDAS,both
18,2026-03-01T00:00:00.000,10004002,10003698.0,1.0,VENDA,1764.0,10001.88,COMERCIAL MUNDO DAS BEBIDAS,both
19,2026-03-01T00:00:00.000,10004002,10022281.0,1.0,VENDA,174.0,1889.64,COMERCIAL MUNDO DAS BEBIDAS,both
20,2026-03-01T00:00:00.000,10004002,10021924.0,1.0,VENDA,712.0,5461.04,COMERCIAL MUNDO DAS BEBIDAS,both
21,2026-03-01T00:00:00.000,10004002,10022636.0,1.0,VENDA,844.0,7207.76,COMERCIAL MUNDO DAS BEBIDAS,both
22,2026-03-01T00:00:00.000,10004002,10001163.0,1.0,VENDA,102.0,1116.90,COMERCIAL MUNDO DAS BEBIDAS,both
23,2026-03-01T00:00:00.000,10004002,10020282.0,1.0,VENDA,679.0,4121.53,COMERCIAL MUNDO DAS BEBIDAS,both
24,2026-03-01T00:00:00.000,10004002,10003698.0,1.0,VENDA,415.0,8109.10,COMERCIAL MUNDO DAS BEBIDAS,both