# Aula 01 – Introdução ao Pandas

## Objetivo da aula

Nesta aula vamos aprender o básico da biblioteca **Pandas**, usada para trabalhar com dados em Python.

Você irá aprender:

- Importar o Pandas
- Ler uma base de dados
- Visualizar os dados
- Entender **Series** e **DataFrame**
- Analisar estrutura e tipos das colunas

# 1. Importando o Pandas

O **Pandas** é a biblioteca mais utilizada para manipulação de dados em Python.

Ela é normalmente importada com o apelido **pd**.

In [2]:
import pandas as pd

# 2. Lendo um arquivo de dados

Vamos carregar uma base utilizando o Pandas.

In [3]:
arquivo = r"C:\Users\Joao.Maria\Documents\curso-python_joao_pedro\Base\Base_analitica_vendas.xlsx"

base_vendas = pd.read_excel(arquivo, sheet_name="Base")

Agora a variável **base_vendas** contém toda a tabela carregada.

# 3. Visualizando os dados

Existem algumas formas simples de visualizar um DataFrame.

### Primeiras linhas da base

In [4]:
base_vendas.head(5)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07

### Ultimas linhas da base

In [5]:
base_vendas.tail(3)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
40618,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94
40619,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10
40620,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88

### Amostragem de dados (linhas aleatórias)

In [6]:
base_vendas.sample(3)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
15813,2026-02-13,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,400,5944.18
35394,2026-02-24,10004237,LOGÍSTICA MUNDO DAS BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015859,Drink Misto Green Apple 269ml,1,VENDA,17,1855.38
21177,2026-02-15,10004231,DISTRIBUIDORA REINO DAS BEBIDAS,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,150,5870.18

### Mostrar a tabela completa

In [7]:
display(base_vendas)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07
...,...,...,...,...,...,...,...,...,...,...,...
40616,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503405,Energéticos de Alta Performance,10023656,Shot Energético Ultra-Concentrado 60ml,1,VENDA,4,1228.52
40617,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021534,Hard Seltzer Limão 310ml,1,VENDA,9,1480.32
40618,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94
40619,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10
40620,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88

### Exibir diretamente a variável

In [8]:
base_vendas

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07
...,...,...,...,...,...,...,...,...,...,...,...
40616,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503405,Energéticos de Alta Performance,10023656,Shot Energético Ultra-Concentrado 60ml,1,VENDA,4,1228.52
40617,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021534,Hard Seltzer Limão 310ml,1,VENDA,9,1480.32
40618,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94
40619,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10
40620,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88

# 4. Estrutura do Pandas

O Pandas possui duas estruturas principais:

| Estrutura | Descrição |
|---|---|
| **Series** | Uma única coluna |
| **DataFrame** | Uma tabela com várias colunas |

## 4.1 Series (uma coluna)

Uma **Series** representa apenas uma coluna da base.

In [9]:
serie_clientes = base_vendas["DESCRICAOCLIENTE"]

serie_clientes

0                ATACADO BRINDE & CIA
1                ATACADO BRINDE & CIA
2                ATACADO BRINDE & CIA
3                ATACADO BRINDE & CIA
4                ATACADO BRINDE & CIA
                     ...
40616    DISTRIBUIDORA ATLETA BEBIDAS
40617    DISTRIBUIDORA ATLETA BEBIDAS
40618    DISTRIBUIDORA ATLETA BEBIDAS
40619    DISTRIBUIDORA ATLETA BEBIDAS
40620    DISTRIBUIDORA ATLETA BEBIDAS
Name: DESCRICAOCLIENTE, Length: 40621, dtype: object

Verificando o tipo da estrutura:

In [10]:
type(serie_clientes)

pandas.core.series.Series

## 4.2 DataFrame (tabela)

Um **DataFrame** representa uma tabela completa.

In [11]:
type(base_vendas)

pandas.core.frame.DataFrame

Também podemos criar um DataFrame selecionando colunas específicas.

In [12]:
dataframe_clientes = base_vendas[["DESCRICAOCLIENTE"]]

dataframe_clientes

                   DESCRICAOCLIENTE
0              ATACADO BRINDE & CIA
1              ATACADO BRINDE & CIA
2              ATACADO BRINDE & CIA
3              ATACADO BRINDE & CIA
4              ATACADO BRINDE & CIA
...                             ...
40616  DISTRIBUIDORA ATLETA BEBIDAS
40617  DISTRIBUIDORA ATLETA BEBIDAS
40618  DISTRIBUIDORA ATLETA BEBIDAS
40619  DISTRIBUIDORA ATLETA BEBIDAS
40620  DISTRIBUIDORA ATLETA BEBIDAS

[40621 rows x 1 columns]

Verificando o tipo:

In [13]:
type(dataframe_clientes)

pandas.core.frame.DataFrame

# 5. Estrutura da base de dados

Podemos analisar a estrutura da base com algumas propriedades importantes.

### Colunas da base

In [14]:
base_vendas.columns

Index(['DATAEMISSAO', 'CODIGOCLIENTE', 'DESCRICAOCLIENTE',
       'CODIGOGRUPOPRODUTO', 'DESCRICAOGRUPOPRODUTO', 'CODIGOPRODUTO',
       'NOMEPRODUTO', 'TIPOFATURAMENTO', 'DESCRICAOTIPOFATURAMENTO', 'VOLUME',
       'VALORLIQUIDO'],
      dtype='object')

Também é possível converter para lista:

In [15]:
list(base_vendas.columns)

['DATAEMISSAO',
 'CODIGOCLIENTE',
 'DESCRICAOCLIENTE',
 'CODIGOGRUPOPRODUTO',
 'DESCRICAOGRUPOPRODUTO',
 'CODIGOPRODUTO',
 'NOMEPRODUTO',
 'TIPOFATURAMENTO',
 'DESCRICAOTIPOFATURAMENTO',
 'VOLUME',
 'VALORLIQUIDO']

### Tamanho da base

Mostra **linhas e colunas**.

In [16]:
base_vendas.shape

(40621, 11)

# 6. Tipos de dados

O Pandas interpreta automaticamente o tipo de cada coluna.

In [17]:
base_vendas.dtypes

DATAEMISSAO                 datetime64[ns]
CODIGOCLIENTE                        int64
DESCRICAOCLIENTE                    object
CODIGOGRUPOPRODUTO                   int64
DESCRICAOGRUPOPRODUTO               object
CODIGOPRODUTO                        int64
NOMEPRODUTO                         object
TIPOFATURAMENTO                      int64
DESCRICAOTIPOFATURAMENTO            object
VOLUME                               int64
VALORLIQUIDO                       float64
dtype: object

# 7. Informações gerais da base

A função **info()** mostra:

- nome das colunas
- tipo de dados
- quantidade de valores nulos

In [18]:
base_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40621 entries, 0 to 40620
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DATAEMISSAO               40621 non-null  datetime64[ns]
 1   CODIGOCLIENTE             40621 non-null  int64
 2   DESCRICAOCLIENTE          40621 non-null  object
 3   CODIGOGRUPOPRODUTO        40621 non-null  int64
 4   DESCRICAOGRUPOPRODUTO     40621 non-null  object
 5   CODIGOPRODUTO             40621 non-null  int64
 6   NOMEPRODUTO               40621 non-null  object
 7   TIPOFATURAMENTO           40621 non-null  int64
 8   DESCRICAOTIPOFATURAMENTO  40621 non-null  object
 9   VOLUME                    40621 non-null  int64
 10  VALORLIQUIDO              40621 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(5), object(4)
memory usage: 3.4+ MB

# 8. Resumo matemático das colunas numéricas

A função **describe()** é o canivete suíço da estatística, onde mostra:

- Média, valor mínimo, valor máximo, desvio padrão
- Foca apenas nas colunas numéricas

In [19]:
base_vendas.describe()

,DATAEMISSAO,CODIGOCLIENTE,CODIGOGRUPOPRODUTO,CODIGOPRODUTO,TIPOFATURAMENTO,VOLUME,VALORLIQUIDO
count,40621,4.062100e+04,4.062100e+04,4.062100e+04,40621.000000,40621.000000,4.062100e+04
mean,2026-02-14 19:14:50.583688192,1.000386e+07,9.030686e+07,1.039773e+07,1.414810,31.207700,3.136858e+03
min,2026-02-01 00:00:00,1.000045e+07,9.001300e+07,1.000116e+07,1.000000,-300.000000,-1.851525e+04
25%,2026-02-08 00:00:00,1.000400e+07,9.001306e+07,1.000778e+07,1.000000,2.000000,3.202900e+02
50%,2026-02-15 00:00:00,1.000421e+07,9.001316e+07,1.001585e+07,1.000000,6.000000,9.080400e+02
75%,2026-02-22 00:00:00,1.000423e+07,9.001317e+07,1.002228e+07,1.000000,25.000000,2.448270e+03
max,2026-02-28 00:00:00,1.000500e+07,9.150341e+07,9.001344e+07,14.000000,1600.000000,1.122164e+06
std,NaN,9.718213e+02,5.928791e+05,4.476117e+06,1.836045,85.129167,1.154109e+04